# Тема 6. Управляющие конструкции языка Python 3

## 6.1.  Логические переменные и организация разветвлений в Python

### 6.1.1. Логические переменные и операции. Операции отношения

Логический тип может принимать одно из двух значений *True* или *False*. В языке *Python* логический тип данных обозначается как *bool*, для приведения других типов данных к логическому существует функция *bool()*, работающая по следующим соглашениям:
+ строки: пустая строка – ложь, непустая строка – истина;
+ числа: нулевое число – ложь, ненулевое число (в том числе и меньшее единицы) – истина;
+ функции – всегда истина.

В Python определены следующие операторы отношения: >, <, ==, !=, >= ,<=.

Из логических переменных и выражений можно строить более сложные  логические выражения с помощью логических операторов: *not*, *or* и *and*.
Логические операции в Python определены для объектов любых типов, но результаты таких операций для операторов and и or не всегда легко понятны.

Логические операторы *and* и *or* в Python используются существенно реже, чем во многих других популярных языках программирования, потому что в Python можно делать любые двойное,тройные и т. д. сравнения, например, $a < x < b$ эквивалентно (x > a) and (x<b).

### 6.1.3. Условный оператор if

В Python простейшая форма условного оператора имеет вид:

```
if логическое_выражение:
	операторы, выполняемые, когда логическое
	выражение истинно
```

В такой форме действия после двоеточия выполняются, если логическое выражение истинно. Если же оно ложно, программа ничего не делает и переходит к следующему оператору.
Полная форма оператора **if**:

```
if логическое_выражение:
	операторы, выполняемые, когда логическое
	выражение истинно
else :
	операторы, выполняемые, когда логическое
	выражение ложно
```

Если нужно последовательно проверить несколько условий, используется расширенная форма с дополнительным оператором **elif** (сокращение от **else if**):

```
if логическое_выражение:
	операторы, выполняемые, когда логическое
	выражение истинно
elif второе_логическое_выражение:
	операторы, выполняемые, когда второе логическое
	выражение истинно
elif третье_логическое_выражение:
	операторы, выполняемые, когда третье логическое
	выражение истинно
...
else :
	операторы, выполняемые, когда все логические
	выражения ложны
```

Дополнительных условий и связанных с ними блоков **elif** может быть сколько угодно. Если некоторое условие оказалось истинным, соответствующий блок кода выполняется, и дальнейшие условия не проверяются.

После двоеточия в конструкциях типа **if**, **else**, **elif** всегда идёт блок, выделенный отступом вправо. Большинство редакторов кода, в том числе и IDLE, делают этот отступ автоматически.

### 6.1.3. Примеры задач

**Задача 6.1**. Решить квадратное уравнение.

**Версия 1.**

In [1]:
import cmath;
a=float(input('a='));
b=float(input('b='));
c=float(input('c='));
d=b*b-4*a*c;
x1=(-b+cmath.sqrt(d))/2/a;
x2=(-b-cmath.sqrt(d))/2/a;
print('x1=',x1,'\t','x2=',x2);

a= 3
b= 5
c= 1


x1= (-0.2324081207560018+0j) 	 x2= (-1.434258545910665+0j)


**Версия 2.**

In [2]:
import math;
a=float(input('a='));
b=float(input('b='));
c=float(input('c='));
d=b*b-4*a*c;
if d>=0:
    x1=(-b+math.sqrt(d))/2/a;
    x2=(-b-math.sqrt(d))/2/a;
    print('x1=',x1,'\t','x2=',x2);
else:
    print('Действительных корней нет');

a= 3
b= 4
c= 6


Действительных корней нет


**Версия 3.**

In [3]:
import cmath, math;
a=float(input('a='));
b=float(input('b='));
c=float(input('c='));
d=b*b-4*a*c;
if d>=0:
    x1=(-b+math.sqrt(d))/2/a;
    x2=(-b-math.sqrt(d))/2/a;
else:
    x1=(-b+cmath.sqrt(d))/2/a;
    x2=(-b-cmath.sqrt(d))/2/a;
print('x1=',x1,'\t','x2=',x2);

a= 4
b= 4
c= 10


x1= (-0.5+1.5j) 	 x2= (-0.5-1.5j)


**Задача 6.2**. Напишите программу решения биквадратного уравнения. Тестовое уравнение $ 5! \cdot x^4 +3! \cdot x^2  - \frac {1}{7} =0 $

**Задача 6.3**. Напишите программу решения кубического уравнения. Алгоритм приведён в курсе по программированию на С(С++). Программа при решении тестовых уравнений $ 2x^3-11.2x^2+11.5x+9=0; 2x^3-11x^2+15x+9=0 $ должна выводить решения $x_1=2.847, x_2=-0.508, x_3=2.366$ и $x_1=-1.416, x_2=2.972+1.143j, x_3=2.972-1.143j $ соответственно. Какое решение имеет уравнение $1! \cdot x^3 +2! \cdot x^2 +3! \cdot x+ 4!=0?$

In [4]:
import cmath, math #Эта строка импортирует модули `cmath` и `math`, которые предоставляют математические функции для работы с комплексными числами и обычными числами соответственно.
a = float(input('Ввод а:'))
b = float(input('Ввод b:'))
c = float(input('Ввод c:'))
d = float(input('Ввод d:'))
r = b / a #Значения переменных `r`, `s` и `t` вычисляются путем деления переменных `b`, `c` и `d` на `a`.
s = c / a
t = d / a
p = (3*s - r*r)/3 #Вычисляются значения переменных `p` и `q` на основе значений `r`, `s` и `t`.
q = (2*r**3)/27 - r*s/3 + t
D = (p/3)**3 + (q/2)**2 #Значение переменной `D` вычисляется на основе значений `p` и `q`.

if d < 0: #Начало условного оператора, который проверяет, является ли значение переменной `d` отрицательным.
    P = cmath.sqrt(-(p**3)/27)#Внутри условия выполняется ряд операций для вычисления корней уравнения в случае, если `d < 0`.

    F = -q / (2*P)
    F = cmath.pi/2 - cmath.atan(F/cmath.sqrt(1-F*F))
    x1 = (2*P**(1/3))*cmath.cos(F/3) - r/3
    x2 = (2*P**(1/3))*(cmath.cos(F/3)+2*cmath.pi/3) - r/3
    x3 = (2*P**(1/3))*(cmath.cos(F/3)+4*cmath.pi/3) - r/3
    print('x1 = ', x1, '\nx2 = ', x2, '\nx3 = ', x3)
else:
    u = (-q/2+cmath.sqrt(D))**(1/3)#В противном случае, когда `d >= 0`, выполняются другие операции для вычисления корней уравнения.
    v = (-q/2-cmath.sqrt(D))**(1/3)
    h = (-u+v)/2 - r/3
    g = cmath.sqrt(3) * (u-v)/2
    x1 = u + v - r/3
    print('x1 = ', x1)

Ввод а: 1
Ввод b: 2
Ввод c: 3
Ввод d: 4


x1 =  (0.42697045480630835+1.199502715028224j)


## 6.2. Операторы цикла Python 

Существует два цикла в Python:

+ while
+ for

### 6.2.1. Цикл while

Общая структура цикла **while**

```
while условие:
	оператор 1
	…
	оператор n
```

Рассмотрим несколько примеров.

In [5]:
N=int(input('N='));
kp=0;
while(N!=0):
    if N<0:
        kp=kp+1;
        if kp==1:
            mx=N;
        elif N>mx:
            mx=N;
    N=int(input('N='));
print(mx);

N= 5
N= -6
N= -2
N= 9
N= 8
N= -1
N= 0


-1


**Операторы управления циклом**. Оператор **continue** начинает следующий проход цикла, минуя оставшееся тело цикла (**for** или **while**). Оператор **break** досрочно прерывает цикл.

 *Полная форма оператора* **while**
```
while условие:
	оператор 1
	…
	оператор n
[else:
	оператор]
```
Как и в неполной форме оператора **while** на каждом шаге оператора  цикла условие, проверяется на истинность.
Если выражение истинно, выполняется тело цикла, иначе тело цикла не выполняется, но выполняется блок *else*.
Если в теле цикла встречается инструкция break, то цикл завершается, при этом блок *else* не выполняется.

###  6.2.2. Оператор for
В Python оператор цикла **for** позволяет пройтись по всем элементам любой последовательности (строки, списка, кортежа и т.д.)
Напомним, что для формирования списков из целочисленных элементов служит функция **range(n,k,d)**.

```
for i in seq:
	оператор1;
	оператор2;
	...
	операторn;
[else:
	оператор]
```
Переменная цикла **i** пробегает все значения из последовательности **seq**. При каждом значении выполняются операторы (тело цикла).
По окончанию цикла выполняется блок *else*.
Если в теле цикла встречается инструкция **break**, то цикл завершается, при этом блок *else* не выполняется.

Примеры задач.

**Задача 1.**

In [6]:
k=int(input('K='));
kch=0;
for i in range(0,k):
    x=int(input('x='));
    if x%2==0:
       kch=kch+1;
       if kch==1:
           mch=x;
           km=0;
       else:
           if x>mch:
               mch=x;
               km=0;
           else:
               if x==mch:
                   km=km+1;
else:
    if kch>0:
        print('max=',mch,'km=',km);
    else:
        print('Нет чётных чисел');

K= 10
x= 22
x= 25
x= 89
x= 12
x= 14
x= 22
x= 17
x= 99
x= 12
x= 6


max= 22 km= 1


**Задача 2.**
```
k=int(input('K='));
kch=0;
for i in range(0,k):
    x=int(input('x='));
    if x>0:
        j=2;
        pr=1;
        while j<=x//2:
            if (x%j==0):
                pr=0;
                break;
            j=j+1;
        if (pr==1):
           kch=kch+1;
           if kch==1:
               mch=x;
               km=0;
           else:
               if x>mch:
                   mch=x;
                   km=0;
               else:
                   if x==mch:
                       km=km+1;
else:
    if kch>0:
        print('max=',mch,'km=',km);
    else:
        print('Нет простых чисел');
```
Это не идеальные коды на *Python*, но эти тексты позволяют приспособиться именно к синтаксису *Python*.

# Тема 7.  Функции в Python

Структура функции в языке Python

```
def name_function (parametr1,  parametr2,…, parametrn):
	operator1;
	operator2;
	operator3;
	...
	operatorn;
	return value;
```
Вызов функции

```
name_function (val1, val2,…, valn)
```

В функциях могут быть параметры, в которых определено значение  по умолчанию

```
def name_function(parametr1,  parametr2,…, parametrn=valuen):
	operator1;
	operator2;
	operator3;
	...
	operatorn;
	return value;
```

В этом случае фактическое значение параметра можно не передавать и будет использовано значение по умолчанию.
Ещё одной интересной особенностью языка Питон является использование именованных аргументов.
Если функция возвращает несколько значений, то можно использовать возвращать их, как кортеж.
```
return (val1, val2, valn)
```

Рассмотрим на примере функции нахождения корней квадратного уравнения.

**Версия 1.**

In [7]:
import math;
def kv(a,b,c):
   d=b*b-4*a*c;
   if (d>=0):
       x1=(-b+math.sqrt(d))/2/a;
       x2=(-b-math.sqrt(d))/2/a;
       pr=1;
   else:
       x1=0;
       x2=0;
       pr=0;
   return (pr,x1,x2);	
a=float(input('a='));
b=float(input('b='));
c=float(input('c='));
y=kv(a,b,c)
if (y[0]==1):
    print('x1=',y[1],' x2=',y[2],'\n');
else:
    print('нет действительных корней')

a= 4
b= 6
c= -8


x1= 0.8507810593582121  x2= -2.350781059358212 



**Версия 2.**

In [8]:
import math;
def kv(a,b,c):
   d=b*b-4*a*c;
   if (d>=0):
       x1=(-b+math.sqrt(d))/2/a;
       x2=(-b-math.sqrt(d))/2/a;
       pr=1;
   else:
       x1=0;
       x2=0;
       pr=0;
   return (pr,x1,x2);	
f=float(input('a='));
g=float(input('b='));
h=float(input('c='));
y=kv(b=f,a=g,c=h)
if (y[0]==1):
    print('x1=',y[1],' x2=',y[2],'\n');
else:
    print('нет действительных корней')

a= 4
b= 6
c= 8


нет действительных корней


# Тема 8.  Примеры циклических алгоритмов на языке Python
**ЗАДАЧА 8.1**. Найти первые **M** чисел Армстронга.
Число Армстронга – натуральное число, равно сумме своих цифр, возведённых в степень, равную количеству его цифр. Работает ли ваш код при M=32? Сравните программы на **Python** и **С**.

**ЗАДАЧА 8.2.** Вводится последовательность из *k* целых элементов. Для всех положительных элементов последовательности вычислить значение факториала. Вывести на экран число и его факториал.

**ЗАДАЧА 8.3.** Вывести на экран первую тысячу чисел Хэмминга. Число Хэмминга - это положительное целое число вида $2^i \cdot 3^j \cdot 5^k$ для некоторых неотрицательных целых чисел i, j, и k. Первое число Хэмминга равно $1 = 2^0 \cdot 3^0 \cdot 5^0$, второе число Хэмминга равно $2 = 2^1 \cdot 3^0 \cdot 5^0$, третье число Хэмминга равно $3 = 2^0 \cdot 3^1 \cdot 5^0$, четвертое число Хэмминга равно $4 = 2^2 \cdot 3^0 \cdot 5^0$, пятое число Хэмминга равно $5 = 2^0 \cdot 3^0 \cdot 5^1$. Работает ли ваш код для вычисления 5000 чисел Хэмминга? Сравните код программ на **Python** и **C

<center> <b>Решение. Алгоритм. Идеи. Коды на С и Python</b> </center>

Числами Хэмминга называются натуральные числа, которые среди своих делителей имеют только степени чисел 2, 3 и 5. Первые 10 упорядоченных по возрастанию чисел Хэмминга образует последовательность 1, 2, 3, 4, 5, 6, 8, 9, 10 и 12. Первому числу этого ряда соответствуют нулевые степени всех сомножителей. Составить программу, которая генерирует первые 1000 чисел Хэмминга.

**Алгоритм № 1.**

Основан на проверке являет ли данное число числом **Хэмминга**.

**Этап 1**. Делим число нацело на 2, до тех пор пока это возможно.

**Этап 2**. Делим число нацело на 3, до тех пор пока это возможно.

**Этап 3**. Делим число нацело на 5, до тех пор пока это возможно.

Если в результате получается число 1, это число Хэмминга.

Код на С.
```
#include <stdio.h>
#include <stdbool.h>
#define uli unsigned long long int
//#define uli  long
bool heming(uli n)
{	for(;n%5==0;n/=5);	for(;n%3==0;n/=3);	for(;n%2==0;n/=2);	return(n==1);
}

int main(int argc, char **argv)
{
	unsigned int count=1,k;
	uli j;
	printf("k=");
	if (scanf("%d",&k)==1)
	{
	for(j=1;count<k;j++)
	if (j%2==0 || j%3==0 || j%5==0) if  (heming(j)) count++;
	printf("%ld",j-1);
	}
	return 0;
}
```
Код на Python.
```
def heming(n):
	while(n%5==0):
		n=n/5
	while(n%3==0):
		n=n/3
	while(n%2==0):
		n=n/2	
	return n==1;
k=int(input("k="));
count=0;
j=1
while(count<k):
	if heming(j):
		count=count+1
		print("№=",count, ",", j)
	j=j+1
	 

```
Программа на С работает значительно быстрее. Но при k>1000, сказывается неэффективность алгоритма, и программа даже на С работает очень долго.

In [22]:
def heming(n):
	while(n%5==0):
		n=n/5
	while(n%3==0):
		n=n/3
	while(n%2==0):
		n=n/2	
	return n==1;
k=int(input("k="));
count=0;
j=1
while(count<k):
	if heming(j):
		count=count+1
		print("№=",count, ",", j)
	j=j+1


k= 100


№= 1 , 1
№= 2 , 2
№= 3 , 3
№= 4 , 4
№= 5 , 5
№= 6 , 6
№= 7 , 8
№= 8 , 9
№= 9 , 10
№= 10 , 12
№= 11 , 15
№= 12 , 16
№= 13 , 18
№= 14 , 20
№= 15 , 24
№= 16 , 25
№= 17 , 27
№= 18 , 30
№= 19 , 32
№= 20 , 36
№= 21 , 40
№= 22 , 45
№= 23 , 48
№= 24 , 50
№= 25 , 54
№= 26 , 60
№= 27 , 64
№= 28 , 72
№= 29 , 75
№= 30 , 80
№= 31 , 81
№= 32 , 90
№= 33 , 96
№= 34 , 100
№= 35 , 108
№= 36 , 120
№= 37 , 125
№= 38 , 128
№= 39 , 135
№= 40 , 144
№= 41 , 150
№= 42 , 160
№= 43 , 162
№= 44 , 180
№= 45 , 192
№= 46 , 200
№= 47 , 216
№= 48 , 225
№= 49 , 240
№= 50 , 243
№= 51 , 250
№= 52 , 256
№= 53 , 270
№= 54 , 288
№= 55 , 300
№= 56 , 320
№= 57 , 324
№= 58 , 360
№= 59 , 375
№= 60 , 384
№= 61 , 400
№= 62 , 405
№= 63 , 432
№= 64 , 450
№= 65 , 480
№= 66 , 486
№= 67 , 500
№= 68 , 512
№= 69 , 540
№= 70 , 576
№= 71 , 600
№= 72 , 625
№= 73 , 640
№= 74 , 648
№= 75 , 675
№= 76 , 720
№= 77 , 729
№= 78 , 750
№= 79 , 768
№= 80 , 800
№= 81 , 810
№= 82 , 864
№= 83 , 900
№= 84 , 960
№= 85 , 972
№= 86 , 1000
№= 87 , 1024
№= 8

**Алгоритм №2.**

Более эффективный алгоритм базируется на построении последовательности чисел Хэмминга. При этом приходится запоминать, какое из ранее найденных чисел необходимо домножить на 2, какое — на 3 и какое — на 5. Из трех возможных вариантов следует выбирать минимальное произведение и запоминать степенью какого числа был минимум. 

Код на С.
```
#include <stdio.h>
int main() 
{
long  x2, x3, x5;
int j,n;
int k2=0,k3=0,k5=0;
printf("n=");
if (scanf("%d",&n)==1 && n>0)
{
long Xam[n];
Xam[0]=1;
printf("   0         1\n");
for(j=1; j<n; j++) 
{
//Очередное число Хэмминга умножаем на 2 3 и 5
x2=Xam[k2]*2; x3=Xam[k3]*3; 
x5=Xam[k5]*5;
//x2 - умножаем на 2
//x3 - умножаем на 3
//x5 - умножаем на 5
//выбираем меьшее из них, это новое число Хэмминга
    if(x2<=x3 && x2<=x5)
    {
		Xam[j]=x2;
//Определяем, что изменять будем x2
		k2++;
    }
    if(x3<=x2 && x3<=x5)
    {
    Xam[j]=x3; k3++;
//Определяем, что изменять будем x3
    }
    if(x5<=x2 && x5<=x3)
    {
    Xam[j]=x5; k5++;
//Определяем, что изменять будем x5
    }
printf("№%4d %9ld\n",j,Xam[j]);
}
}
else printf("Ошибка ввода данных");
return 0;
}
```
Код на Питоне
```
from numpy import *
k2=0
k3=0
k5=0
n=int(input("n="))
Xam=[0]*n
Xam[0]=1;
print("№ 0 1");
for j in range(1,n):
#Очередное число Хэмминга умножаем на 2 3 и 5
#x2 - умножаем на 2
#x3 - умножаем на 3
#x5 - умножаем на 5
	x2=Xam[k2]*2;
	x3=Xam[k3]*3;
	x5=Xam[k5]*5;
#выбираем меьшее из них, это новое число Хэмминга
	if x2<=x3 and x2<=x5:
		Xam[j]=x2;
		k2+=1;
#Определяем, что изменять будем x2
		
	if x3<=x2 and x3<=x5:
		Xam[j]=x3;
		k3+=1;
#Определяем, что изменять будем x3
	if x5<=x2 and x5<=x3:
		Xam[j]=x5
		k5+=1;
#Определяем, что изменять будем x5
	print("№",j,Xam[j])
```

In [28]:
from numpy import *
k2=0
k3=0
k5=0
n=int(input("n="))
Xam=[0]*n
Xam[0]=1;
print("№ 0 1");
for j in range(1,n):
#Очередное число Хэмминга умножаем на 2 3 и 5
#x2 - умножаем на 2
#x3 - умножаем на 3
#x5 - умножаем на 5
	x2=Xam[k2]*2;
	x3=Xam[k3]*3;
	x5=Xam[k5]*5;
#выбираем меьшее из них, это новое число Хэмминга
	if x2<=x3 and x2<=x5:
		Xam[j]=x2;
		k2+=1;
#Определяем, что изменять будем x2
		
	if x3<=x2 and x3<=x5:
		Xam[j]=x3;
		k3+=1;
#Определяем, что изменять будем x3
	if x5<=x2 and x5<=x3:
		Xam[j]=x5
		k5+=1;
#Определяем, что изменять будем x5
	print("№",j,Xam[j])


n= 100


№ 0 1
№ 1 2
№ 2 3
№ 3 4
№ 4 5
№ 5 6
№ 6 8
№ 7 9
№ 8 10
№ 9 12
№ 10 15
№ 11 16
№ 12 18
№ 13 20
№ 14 24
№ 15 25
№ 16 27
№ 17 30
№ 18 32
№ 19 36
№ 20 40
№ 21 45
№ 22 48
№ 23 50
№ 24 54
№ 25 60
№ 26 64
№ 27 72
№ 28 75
№ 29 80
№ 30 81
№ 31 90
№ 32 96
№ 33 100
№ 34 108
№ 35 120
№ 36 125
№ 37 128
№ 38 135
№ 39 144
№ 40 150
№ 41 160
№ 42 162
№ 43 180
№ 44 192
№ 45 200
№ 46 216
№ 47 225
№ 48 240
№ 49 243
№ 50 250
№ 51 256
№ 52 270
№ 53 288
№ 54 300
№ 55 320
№ 56 324
№ 57 360
№ 58 375
№ 59 384
№ 60 400
№ 61 405
№ 62 432
№ 63 450
№ 64 480
№ 65 486
№ 66 500
№ 67 512
№ 68 540
№ 69 576
№ 70 600
№ 71 625
№ 72 640
№ 73 648
№ 74 675
№ 75 720
№ 76 729
№ 77 750
№ 78 768
№ 79 800
№ 80 810
№ 81 864
№ 82 900
№ 83 960
№ 84 972
№ 85 1000
№ 86 1024
№ 87 1080
№ 88 1125
№ 89 1152
№ 90 1200
№ 91 1215
№ 92 1250
№ 93 1280
№ 94 1296
№ 95 1350
№ 96 1440
№ 97 1458
№ 98 1500
№ 99 1536


**ЗАДАЧА 8.4.** Вводится последовательность целых чисел, 0 — конец последовательности. Найти наибольшее из чисел, сумма цифр которых является простым числом.

# Тема 9. Массивы в Python
Для работы с массивами понадобится модуль numpy. Существует несколько способов создания массивов, рассмотрим их последовательно.

## 9.1  Преобразование списка в массив

Можно создать массив из списка с помощью функции **array**. Нумерация в массиве идёт с 0.

In [9]:
from numpy import *
zyu=array([0.6,7.5,7.8,-16,97.67,-12.1])
print(zyu)
print(type(zyu))
print(zyu[0],zyu[2])

[  0.6    7.5    7.8  -16.    97.67 -12.1 ]
<class 'numpy.ndarray'>
0.6 7.8


**ndarray** – это тип (а вообще говоря объект) многомерных массивов из модуля numpy.
Наиболее важные атрибуты объектов **ndarray** (https://habr.com/ru/post/121031/):

+ **ndarray.ndim** – число измерений массива.
+ **ndarray.shape** – кортеж размерности ndim, определяющий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m).
+ **ndarray.size** – число всех элементов массива. Равно произведению всех элементов атрибута shape.
+ **ndarray.dtype** – объект, описывающий тип элементов массива. NumPy позволяет определить следующие типы здесь предоставляет целый букет возможностей, например: bool_, character, int_, int8 (знаковое 8-битное целое), int16 (знаковое 16-битное целое), int32 (знаковое 32-битное целое), int64 (знаковое 64-битное целое),uint8, uint16, uint32, uint64 (беззнаковые 8-, 16-, 32-, 64-битные целые)  float_, float32, float64 (вещественные числа обычной и двойной точности), complex_, complex64, complex128 (комплексные числа обычной и двойной точности), object_.
+ **ndarray.itemsize** – размер каждого элемента массива в байтах.

При создании с помощью функции array можно указать тип переменной с помощью параметра dtype, рассмотрим пример использования array для матрицы комплексных чисел.


In [10]:
C = array ([[1 +4j, 2-6j, 3,-5-6j], [4-11j, 5, 6,5j-1]],  dtype = complex64)
print(C)
# обращение к элементам матрицы С[i,j]

[[ 1. +4.j  2. -6.j  3. +0.j -5. -6.j]
 [ 4.-11.j  5. +0.j  6. +0.j -1. +5.j]]


## 9.2.  Создание массива из диапазона
Диапазон – это конечно тоже список, однако при формировании самого диапазона есть особенности, которые заслуживают рассмотрения.
Первый пример: создание массива из диапазона, созданного с помощью функции range.

In [11]:
a=array(range(20))
print(a)
b=array(range(1,201,10))
print(b)
q=array(range(11,21))
print(q)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  1  11  21  31  41  51  61  71  81  91 101 111 121 131 141 151 161 171
 181 191]
[11 12 13 14 15 16 17 18 19 20]


В *numpy* есть функция **arange**, позволяющая сразу создать диапазон вещественных чмсел. Все её аргументы вещественные, и как следствие генерируемый с помощью array массив состоит из вещественных чисел. Пример

In [12]:
x=array(arange(-2*pi,2*pi,pi/3))
y=sin(x)
z=cos(x)
u=sin(cos(x))
for i in range(len(x)):
    print(x[i], y[i],z[i],u[i])

-6.283185307179586 2.4492935982947064e-16 1.0 0.8414709848078965
-5.235987755982989 0.8660254037844386 0.5000000000000001 0.4794255386042031
-4.188790204786391 0.8660254037844388 -0.4999999999999996 -0.4794255386042027
-3.141592653589794 7.657137397853899e-16 -1.0 -0.8414709848078965
-2.0943951023931966 -0.866025403784438 -0.500000000000001 -0.4794255386042039
-1.0471975511965992 -0.8660254037844394 0.4999999999999988 0.47942553860420195
-1.7763568394002505e-15 -1.7763568394002505e-15 1.0 0.8414709848078965
1.0471975511965956 0.8660254037844376 0.5000000000000018 0.47942553860420456
2.094395102393193 0.8660254037844398 -0.4999999999999979 -0.4794255386042012
3.1415926535897896 3.675178358715236e-15 -1.0 -0.8414709848078965
4.188790204786388 -0.866025403784437 -0.5000000000000027 -0.47942553860420534
5.235987755982986 -0.8660254037844399 0.4999999999999978 0.47942553860420106


Таким образом мы имеем функции range и arange, позволяющие создавать массивы диапазоны из целых и вещественных чисел соответственно.

Альтернативой им является функция **linspace**.
```
linspace(xn, xk, n, flag=True),
```
здесь
xn – начальное значение диапазона,
xk – конечное значение диапазона,
n – количество элементов в диапазоне,
flag – логическая переменная, определяющая включать или нет конечное значение в диапазон по умолчанию включать (True).
Примеры

In [13]:
a=arange(0,2,0.1);
print(a);
b=linspace(0,2,11);
print(b);
c=linspace(0,2,11,False)
print(c);

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[0.         0.18181818 0.36363636 0.54545455 0.72727273 0.90909091
 1.09090909 1.27272727 1.45454545 1.63636364 1.81818182]


Использование срезов в массивах рассмотрим на примере.

In [14]:
a=arange(0,2,0.1);
print(a);
# В массив a1 включаются элементы массива a с 0 по 4
a1=a[0:5]
print(a1)
b=linspace(0,2,11);
print(b);
# В массив b1 включаются 0, 3, 6, 9 элементы массива b
b1=b[0:len(b):3]
print(b1)
c=linspace(0,2,11,False)
print(c);
# Вывод 0, 3, 6 элементов массива c
print(c[0:8:3]);

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]
[0.  0.1 0.2 0.3 0.4]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[0.  0.6 1.2 1.8]
[0.         0.18181818 0.36363636 0.54545455 0.72727273 0.90909091
 1.09090909 1.27272727 1.45454545 1.63636364 1.81818182]
[0.         0.54545455 1.09090909]


Срез – это массив, образованный из другого.

Python унаследовал из Фортрана операции над массивами.

Над массивами (срез – это тоже массив) одинакового размера определены поэлементные операции сложения, вычитания, умножения и деления, а также прибавлять и вычитать к массиву число, умножать и делить массивы на число, а также применять встроенные функции над массивом целиком.

Библиотека numpy содержит встроенные функции над массивами.

```
random.random((rows, column))
```
или 
```
random.random
```

Функция возвращает массив с заданным количеством измерений, где каждый элемент генерируется случайным образом в диапазоне (0,1).


In [15]:
import numpy
a=numpy.random.random((2,4))
print(a)

[[0.01750953 0.31290723 0.0536582  0.62932694]
 [0.27783535 0.18716626 0.53844157 0.90159244]]


**sum()** - функция вернет сумму всех элементов.

In [16]:
import numpy
a=numpy.random.random((8,5))
print(a)
print(a.sum())

[[0.15266998 0.22131932 0.17555971 0.03992848 0.45249964]
 [0.9595347  0.42136828 0.63835606 0.80524582 0.96694022]
 [0.41883305 0.7061089  0.54260786 0.25526201 0.06653948]
 [0.10349522 0.47168023 0.37690102 0.60595999 0.60782714]
 [0.72580772 0.10565432 0.4991443  0.14583537 0.67474715]
 [0.65711111 0.80831342 0.10133886 0.97115366 0.30549158]
 [0.28607856 0.16448489 0.97202798 0.29569921 0.93026836]
 [0.23849826 0.84312877 0.29120693 0.77634346 0.50564136]]
19.28661238733396


**min()** - функция вернет элемент с минимальным значением.

In [17]:
import numpy
a=numpy.random.random((7,5))
print(a)
print(a.min())

[[0.77149182 0.79893159 0.22157641 0.95732946 0.05642875]
 [0.29419551 0.05103586 0.45310824 0.01092762 0.55200186]
 [0.72756696 0.63922277 0.98933098 0.84764502 0.87693571]
 [0.00621383 0.15325487 0.7659303  0.47694585 0.74416824]
 [0.74592875 0.79634564 0.09735086 0.83317182 0.04351101]
 [0.16673153 0.26583738 0.47772435 0.35216049 0.11611406]
 [0.92149015 0.68534293 0.29356561 0.06482226 0.58361857]]
0.006213826819149726


**max()** - функция вернет элемент с максимальным значением.

In [18]:
import numpy
a=numpy.random.random((5,6))
print(a)
print(a.max())

[[0.62718471 0.59663668 0.90987202 0.48814355 0.71167818 0.89688059]
 [0.33895723 0.58550628 0.84693081 0.70795764 0.73577406 0.26352627]
 [0.27260405 0.69290942 0.72700794 0.54190371 0.94214145 0.23892933]
 [0.57899127 0.35016125 0.94743645 0.58371056 0.75139507 0.09236968]
 [0.0099272  0.63328276 0.82230612 0.04245116 0.72631763 0.58350263]]
0.9474364452684078


**zeros((rows, columns), dtype)** или **random.zeros(n)** - функция создаст массив нулевых значений с заданным количеством измерений


In [19]:
import numpy 
a=numpy.zeros((5,7))
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**ones((rows,columns), dtype)**  или **random.ones(n)** - функция создаст массив единиц с заданным количеством измерений


**empty((rows,columns))** или **random.empty(n)** функция создаст массив, содержимое которого будет пустым.

In [21]:
numpy.empty((3,5))

array([[ 4.64690391e-310,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000, -7.49863433e-206]])

**Определение и инициализация массивов и матриц в Python3**
```
#Создаём массив и запоняем нулями
b = full(11, 0)
#Создаём матрицу и запоняем единицами
c = full((11,16), 1)
```

In [25]:
import numpy
n=int(input("n="))
b = full(n, 0)
print(b)
m=int(input("m="))
k=int(input("k="))
c = full((k,m), 1)
print(c)

n= 7


[0 0 0 0 0 0 0]


m= 3
k= 9


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [26]:
c[0][2]=13

In [27]:
print(c)

[[ 1  1 13]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]]
